@startuml 03-er-auth
title Modelo ER — Tabla security_user

entity "security_user" as users {
  *pkid : BIGINT <<PK>>
  *id : UUID <<UNIQUE>>
  *username : VARCHAR(150) <<UNIQUE>>
  *email : VARCHAR(254) <<UNIQUE>>
  *password : VARCHAR(128)
  *first_name : VARCHAR(50)
  *last_name : VARCHAR(50)
  *is_active : BOOLEAN
  *is_staff : BOOLEAN
  *date_joined : DATETIME
  *created_at : DATETIME
  *updated_at : DATETIME
  foto : VARCHAR(1024)
  last_login : DATETIME
}
@enduml
